version: "3"
services:
  api:
    build: ./apps/api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./test.db

  web:
    build: ./apps/web
    ports:
      - "3000:3000"
      PYTHONPATH=.